version: '3'

volumes:
  pg_data:
  static_data:
  media_data:


services:
  db:
    container_name: me-shop-postgres
    image: postgres:15.4
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env
    restart: always

  me-backend-app:
    container_name: me-backend-app
    image: timrybakov/misexpress_backend:latest
    volumes:
      - static_data:/backend_static
      - media_data:/app/media/
    restart: always
    env_file:
      - .env
    depends_on:
      - db
    command: sh -c "./entrypoint.sh"

  me-frontend-app:
    image: timrybakov/misexpress_frontend:latest
    container_name: me-frontend-app
    depends_on:
      - me-backend-app
    command: sh -c "npm run start"
    restart: always

  nginx:
    image: timrybakov/misexpress_gateway:latest
    container_name: me-gateway-app
    depends_on:
      - me-backend-app
      - me-frontend-app
    ports:
      - 8000:80
    volumes:
      - static_data:/staticfiles
      - media_data:/media
    restart: always
