version: '3.7'
services:
  db:
    image: postgres:15.4
    restart: always
    container_name: $POSTGRES_HOST
    env_file: backend/.env
    ports:
      - '5432:5432'
    volumes:
      - pg_data:/var/lib/postgresql/data

  me-backend-app:
    image: kuzilya/misexpress_backend:latest
    restart: always
    container_name: me-backend-app
    env_file: backend/.env
    depends_on:
      - db
    volumes:
      - static_data:/app/static
      - media_data:/app/media
    command: sh -c "./entrypoint.sh"
    ports:
      - '8000:8000'

  me-frontend-app:
    image: kuzilya/misexpress_frontend:latest
    container_name: me-frontend-app
    depends_on:
      - me-backend-app
    command: sh -c "npm run start"
    ports:
      - '3000:3000'
    restart: always

  nginx:
    image: kuzilya/misexpress_gateway:latest
    container_name: me-gateway-app
    depends_on:
      - me-backend-app
      - me-frontend-app
    ports:
      - '80:80'
      - '8800:8800'
    volumes:
      - static_data:/var/www/api/static/
      - media_data:/var/www/api/media/
    restart: always
volumes:
  pg_data:
  static_data:
  media_data:
